name: Build twitter image

on:
  repository_dispatch:
    types: [opened, deleted, tweet]
  schedule:
    # Runs every 6 hour
    - cron: '0 */6 * * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
    - uses: actions/checkout@v2
    
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.0'
        
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          any::remotes
          
    - name: Install Package Dependencies
      run: |-
        Rscript -e 'remotes::install_github("gadenbuie/tweetrmd", auth_token=Sys.getenv("GITHUB_PAT"))'
        Rscript -e 'remotes::install_github("rstudio/webshot2", auth_token=Sys.getenv("GITHUB_PAT"))'
        Rscript -e 'install.packages("rtweet")'
        
    - name: Generate Twitter Image
      env:
        ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      run: Rscript -e "source('tweet.R')"

    - name: Commit and push if changed
      run: |-
        git config --global user.email "github-action-bot@example.com"
        git config --global user.name "GitHub Twitter"
        git add .
        git commit -m "Updated README" -a || echo "No changes to commit"
        git push

